src/shared/runModifications.js, src/tetris-planning/TetrisPlanningButton.js
=> [fix-tetris-plunning-button] move tetris button

src/bug-template/BugTemplate.js
Fix disappearing of buttons in bug-template while creating issues.
=> [#22] Fix disappearing of buttons in bug-template

src/column-limits/WIPLimits.js, src/tetris-planning/TetrisPlanning.js
Починил проблему с отображением лимитов колонок при привышении лимита бэкграунд красится только в первом sweemline
=> #28 bug with column wip-limits

src/charts/AddSlaLine.js
+ добавляет возможность просмотра / манипулирования (без сохранений) SLA для обычных пользователей доски
=> [#37] Добавляет линию предварит. изменений для SLA

src/charts/AddChartGrid.js
=> [#55] 1,2 chart + days value

src/swimlane/SwimlaneStats.js
=> [#51] add jira 8 column headers

src/person-limits/personLimitsModal.html, src/person-limits/personLimitsModal.js
=> [#53] multi edit

src/charts/utils.js
=> [#62] Support cube-root power scale for Grid and SLA

src/column-limits/WIPLimits.js, src/person-limits/PersonLimits.js, src/shared/PageModification.js, src/swimlane/SwimlaneStats.js
При использовании настройки "Column Constraint = Issue Count, excluding sub-task", необходимо для персональных WIP-лимитов исключение из подсчета sub-task-ки
=> [#64] Fixed Sum issues for personal WIP-limit

src/charts/AddSlaLine.js
=> [#66] Show percentage label under SLA line

src/column-limits/WIPLimitsSettings.js
We have the error of JIRA 7.1.x for found columns on the settings page of Columns.
JIRA 7.1.x has other css classes for Columns.
=> [#68] fixed trouble for  JIRA 7.1.x

src/column-limits/SettingsPage/index.js, src/person-limits/personLimitsModal.html, src/shared/getPopup.js
Исправляет отображение модальных окон на Jira v.8.12.3:
* Исправляет ошибки с поведением модалок на лимитах
* Исправляет отображение мультиселекта на пользовательских лимитах групп
=> Исправляет отображение модальных окон

src/bug-template/BugTemplate.js, src/bug-template/styles.css
added save and write text template for create sub-tasks
=> [#21] use templates in a popup for create sub-task

src/field-limits/BoardPage/index.js
=> [#119] fixed bug 119 with estimate WIP-limits by Customer Field of Multivalue field

src/field-limits/SettingsPage/index.js
Показывать WIP-лимиты для возможности удаления не корректных записей которые занесены в БД, но после измменения доски не могут показаться
=> [#122] show incorrect WIP-limit for opportunity be deleted

src/person-limits/PersonLimits.js
Кликаешь на аватар иконки персонально WIP-лимита - и можно скрыть или показать карточки которые не отностяся к тому по чьей аватарке был клик
=> Показать или скрыть карточки по клику на аватар

src/person-limits/PersonLimits.js
for click by a personal WIP-limit:
1. all languages (not only eng.);
2. using choosing a few;
=> [#136] fixed bug with click by a personal WIP-limit

src/charts/AddSlaLine.js, src/charts/utils.js
Показать диапазон процентиля как наиболее приближенное к методу вычисления
=> [#70] show rect procentile

src/person-limits/PersonLimits.js
Показать и скрыть группы сабтасков если в них есть или нет карточек скрытых по клику на personal WIP-лимиты
=> [#139] show or hide group sub-task by click on personal WIP-limit

src/person-limits/personLimitsModal.html, src/person-limits/personLimitsModal.js
Editing personal WIP-limit https://github.com/TinkoffCreditSystems/jira-helper/issues/106
=> [#106] Editing personal WIP-limit

src/shared/jiraApi.js
=> [#153] Look for exact match first

.eslintrc, .gitignore, src/field-limits/SettingsPage/htmlTemplates.js, src/field-limits/SettingsPage/index.js, src/field-limits/SettingsPage/styles.css
From https://github.com/Tinkoff/jira-helper/issues/106
at the request of Maxim Frolov
https://github.com/Tinkoff/jira-helper/issues/106#issuecomment-877818996
=> #106 new function — "edit" field WIP-limits
